server:
  port: 0

spring:
  # BASE DE DATOS
  r2dbc:
    password: postgresql1234
    url: r2dbc:postgresql://cloud.vscperu.com:5432/municajdb
    username: postgresql
    pool:
      max-size: 10
      max-create-connection-time: 10s
  # RABBITMQ
  rabbitmq:
    host: cloud.vscperu.com
    port: 5672
    username: ${rabbitmqusername}
    password: ${rabbitmqpassword}

# SWAGGER
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

# EUREKA
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://cloud.vscperu.com:8761/eureka

# ACTUATOR - MONITOR
management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh